import type { AssessmentCategory } from '@/lib/assessment-api';

type CategoryOptionValue = Exclude<AssessmentCategory, null> | 'none';

const assessmentCategoryLabels: Record<CategoryOptionValue, string> = {
  none: 'Uncategorized',
  quiz: 'Quiz',
  midterm: 'Midterm',
  final: 'Final',
  practice: 'Practice',
  other: 'Other',
};

export const APP_COPY = {
  nav: {
    library: 'Library',
    upload: 'Upload',
    editor: 'Editor',
  },
  library: {
    label: 'Teacher Library',
    title: 'Assessments',
    subtitle: 'Browse existing assessments and jump back into the editor to adjust drafts.',
    totalCount: (value: number) => `${value} total`,
    filteredCount: (value: number) => `${value} shown`,
    ctaLabel: 'Start new upload',
    entryLabel: 'Assessment',
    errorTitle: 'Failed to load assessments',
    errorBody: 'Check that the API is running on port 3001.',
    emptyTitle: 'No assessments yet',
    emptyBody: 'Create a new assessment in the editor to get started.',
    filteredEmptyTitle: 'No matching assessments',
    filteredEmptyBody: 'Try broadening filters or clear them to view all assessments.',
    draftAvailable: 'Draft available',
    noDraft: 'No draft version',
    updatedAt: (value: string) => `Updated ${value}`,
    openEditor: 'Open editor',
    subjectGradeFallback: 'Subject and grade not provided',
    filters: {
      title: 'Refine results',
      searchLabel: 'Search',
      searchPlaceholder: 'Search by title',
      subjectLabel: 'Subject',
      allSubjects: 'All subjects',
      gradeLabel: 'Grade',
      allGrades: 'All grades',
      categoryLabel: 'Category',
      draftLabel: 'Draft status',
      categoryAll: 'All categories',
      draftAll: 'All statuses',
      withDraft: 'With draft',
      withoutDraft: 'Without draft',
      clearAll: 'Clear all',
      activeFilters: 'Active filters',
    },
  },
  upload: {
    label: 'Create Test',
    title: 'Upload',
    subtitle: 'Drop a DOCX or PDF file to create a new assessment draft.',
    steps: {
      upload: 'Upload',
      parse: 'Parse',
      review: 'Review',
    },
    dropTitle: 'Add your file',
    dropBody: 'Drag a document here or browse to upload.',
    dropAction: 'Drop your file here',
    dropHint: 'PDF or DOCX, up to 20MB.',
    dropBrowse: 'Browse files',
    selectedFileLabel: 'Selected file',
    replaceFile: 'Replace file',
    uploadFileLabel: 'Upload file',
    uploadHelper: 'Max size 20MB. PDF or DOCX.',
    retentionNotice:
      'Your upload is available in this browser for 24 hours. Download your work before it expires.',
    providerNotice: 'Parsing may send the document to the configured AI provider.',
    sampleSourcesTitle: 'Sample PDF',
    sampleSourcesBody: 'Choose a sample PDF with one click.',
    sampleLabel: 'Clase worksheet',
    sampleUseButton: (label: string) => `Use ${label} sample PDF`,
    samplePreviewButton: 'Preview PDF',
    sampleUseLoading: 'Fetching...',
    sampleFetchFailed: 'Failed to fetch the sample PDF. Please try again.',
    uploadButton: 'Upload and parse',
    uploadingButton: 'Uploading...',
    selectFileError: 'Select a file to upload.',
    invalidFile: 'Please upload a PDF or DOCX file.',
    uploadFailed: 'Upload failed. Please try again.',
    uploadInterrupted: 'Connection interrupted during upload.',
    uploadTimeout: 'Upload timed out.',
    uploadRetryHint: 'Please retry your upload.',
    uploadInProgress: 'This upload is already in progress. Please wait a moment.',
    uploadRetryNewAttempt: 'Previous upload attempt failed. Please retry with a new attempt.',
    untitledAssessment: 'Untitled assessment',
    parsingTitle: 'Parsing status',
    parsingReadyTitle: 'Ready when you are',
    parsingReadyBody: 'Upload a PDF or DOCX to start extraction and draft generation.',
    parsingBody: (fileName?: string | null) =>
      fileName ? `Last upload: ${fileName}` : 'Waiting for file upload.',
    timelineUploadHint: 'File received successfully',
    timelineParseHint: 'Extracting structure and generating draft questions',
    timelineReviewHint: 'Open and refine the generated draft',
    flowTitle: 'How it works',
    flowBody: 'Move from file upload to print-ready output in four guided steps.',
    flowSteps: {
      upload: 'Upload a PDF or DOCX file',
      extract: 'Extract questions automatically',
      edit: 'Review and manually edit in editor',
      print: 'Open print editor and print',
    },
    browseLibrary: 'Browse library',
    retryUpload: 'Retry upload',
    selectFileRetry: 'Select a file to retry.',
    parsingNone: 'No parsing job yet.',
    openEditor: 'Open in editor',
    questions: (value: number) => `Questions: ${value}`,
    parser: (value: string) => `Parser: ${value}`,
    elapsed: (value: number) => `Elapsed: ${value}s`,
    updatedAt: (value: string) => `Updated ${value}`,
  },
  status: {
    queued: 'Queued',
    running: 'Parsing',
    success: 'Completed',
    failed: 'Failed',
    notStarted: 'Not started',
    unknown: 'Unknown',
  },
  assessmentCategoryLabels,
} as const;
