import type { AssessmentCategory } from '@/lib/assessment-api';

type CategoryOptionValue = Exclude<AssessmentCategory, null> | 'none';

const assessmentCategoryLabels: Record<CategoryOptionValue, string> = {
  none: '未分類',
  quiz: '小テスト',
  midterm: '中間試験',
  final: '期末試験',
  practice: '演習',
  other: 'その他',
};

export const APP_COPY = {
  nav: {
    library: '課題一覧',
    upload: 'アップロード',
    editor: 'エディター',
  },
  library: {
    label: '課題ライブラリ',
    title: '課題一覧',
    subtitle: '既存の課題を確認し、エディターで下書きを調整できます。',
    totalCount: (value: number) => `合計 ${value} 件`,
    filteredCount: (value: number) => `${value} 件を表示`,
    ctaLabel: '新しいアップロードを開始',
    entryLabel: '課題',
    errorTitle: '課題の取得に失敗しました',
    errorBody: 'APIが3001で動作しているか確認してください。',
    emptyTitle: 'まだ課題がありません',
    emptyBody: 'エディターで新しい課題を作成してください。',
    filteredEmptyTitle: '条件に一致する課題がありません',
    filteredEmptyBody: '条件を緩めるか、フィルターをクリアして再度お試しください。',
    draftAvailable: '下書きあり',
    noDraft: '下書きなし',
    updatedAt: (value: string) => `更新日 ${value}`,
    openEditor: 'エディターを開く',
    subjectGradeFallback: '科目・学年の情報なし',
    filters: {
      title: '絞り込み',
      searchLabel: '検索',
      searchPlaceholder: 'タイトルで検索',
      subjectLabel: '科目',
      allSubjects: 'すべての科目',
      gradeLabel: '学年',
      allGrades: 'すべての学年',
      categoryLabel: 'カテゴリ',
      draftLabel: '下書き状態',
      categoryAll: 'すべてのカテゴリ',
      draftAll: 'すべての状態',
      withDraft: '下書きあり',
      withoutDraft: '下書きなし',
      clearAll: 'すべてクリア',
      activeFilters: '適用中の条件',
    },
  },
  upload: {
    label: '課題を作成',
    title: 'アップロード',
    subtitle: 'DOCX または PDF をドラッグして課題の下書きを作成します。',
    steps: {
      upload: 'アップロード',
      parse: '解析',
      review: 'レビュー',
    },
    dropTitle: 'ファイルを追加',
    dropBody: 'ここにファイルをドロップするか、参照してアップロードします。',
    dropAction: 'ファイルをここにドロップ',
    dropHint: 'PDF または DOCX（最大 20MB）。',
    dropBrowse: 'ファイルを参照',
    selectedFileLabel: '選択中のファイル',
    replaceFile: 'ファイルを差し替え',
    uploadFileLabel: 'ファイルをアップロード',
    uploadHelper: '最大 20MB。PDF または DOCX。',
    retentionNotice:
      'アップロードしたデータは、このブラウザーで24時間利用できます。期限前にダウンロードしてください。',
    providerNotice: '解析のため、文書が設定されたAIプロバイダーに送信される場合があります。',
    sampleSourcesTitle: 'サンプルPDF',
    sampleSourcesBody: 'ワンクリックでサンプルPDFを選択できます。',
    sampleLabel: 'Claseの練習問題',
    sampleUseButton: (label: string) => `${label}のサンプルPDFを使う`,
    samplePreviewButton: 'PDFをプレビュー',
    sampleUseLoading: '取得中...',
    sampleFetchFailed: 'サンプルPDFの取得に失敗しました。もう一度お試しください。',
    uploadButton: 'アップロードして解析',
    uploadingButton: 'アップロード中...',
    selectFileError: 'アップロードするファイルを選択してください。',
    invalidFile: 'PDF または DOCX のファイルを選択してください。',
    uploadFailed: 'アップロードに失敗しました。もう一度お試しください。',
    uploadInterrupted: 'アップロード中に接続が中断されました。',
    uploadTimeout: 'アップロードがタイムアウトしました。',
    uploadRetryHint: 'もう一度アップロードしてください。',
    uploadInProgress: 'このアップロードはすでに処理中です。しばらく待ってください。',
    uploadRetryNewAttempt:
      '前回のアップロードは失敗しました。新しい試行として再アップロードしてください。',
    untitledAssessment: '無題の課題',
    parsingTitle: '解析ステータス',
    parsingReadyTitle: '準備完了',
    parsingReadyBody: 'PDF または DOCX をアップロードすると、抽出と下書き生成を開始します。',
    parsingBody: (fileName?: string | null) =>
      fileName ? `最終アップロード: ${fileName}` : 'アップロード待機中です。',
    timelineUploadHint: 'ファイルを受け付けました',
    timelineParseHint: '構造を抽出し、設問の下書きを生成しています',
    timelineReviewHint: '生成された下書きを開いて調整します',
    flowTitle: '使い方',
    flowBody: '4つのステップで、アップロードから印刷まで進められます。',
    flowSteps: {
      upload: 'PDF または DOCX をアップロード',
      extract: '設問を自動抽出',
      edit: 'エディターで確認・手動編集',
      print: '印刷エディターで確認して印刷',
    },
    browseLibrary: 'ライブラリを見る',
    retryUpload: '再アップロード',
    selectFileRetry: '再試行するにはファイルを選択してください。',
    parsingNone: '解析中のファイルはまだありません。',
    openEditor: 'エディターで開く',
    questions: (value: number) => `設問数: ${value}`,
    parser: (value: string) => `パーサー: ${value}`,
    elapsed: (value: number) => `経過: ${value}秒`,
    updatedAt: (value: string) => `更新 ${value}`,
  },
  status: {
    queued: '待機中',
    running: '解析中',
    success: '完了',
    failed: '失敗',
    notStarted: '未開始',
    unknown: '不明',
  },
  assessmentCategoryLabels,
} as const;
