import type { AssessmentCategory, QuestionType } from '@/lib/assessment-api';

type CategoryOptionValue = Exclude<AssessmentCategory, null> | 'none';

const questionTypeLabels: Record<QuestionType, string> = {
  multiple_choice: '選択式',
  true_false: '正誤',
  short_answer: '短答',
  written: '記述',
  other: 'その他',
};

const assessmentCategoryLabels: Array<{ value: CategoryOptionValue; label: string }> = [
  { value: 'none', label: '未分類' },
  { value: 'quiz', label: '小テスト' },
  { value: 'midterm', label: '中間試験' },
  { value: 'final', label: '期末試験' },
  { value: 'practice', label: '演習' },
  { value: 'other', label: 'その他' },
];

export const EDITOR_COPY = {
  header: {
    draftLabel: '下書き',
    titlePrefix: '生成された課題を確認:',
    subtitle: '',
    studentViewLabel: '全体プレビュー',
    assessmentSettingsLabel: '設定',
    printEditorLabel: 'プリント',
  },
  layoutOptions: {
    studio: 'スタジオ',
    document: 'ドキュメント',
  },
  a11y: {
    layoutToggle: 'エディターのレイアウト',
  },
  actions: {
    newAssessment: '新規',
    duplicateAssessment: '複製',
    more: 'その他',
    saveChanges: '保存',
    save: '保存',
    confirmNext: '保存して次へ',
    discard: '破棄',
    close: '閉じる',
    studentView: '学生ビュー',
    addQuestion: '設問を追加',
    moveUp: '上へ移動',
    moveDown: '下へ移動',
    deleteQuestion: '設問を削除',
    addChoice: '選択肢を追加',
    generateTargetQuestion: '60%目標で書き換え（現在の設問を置換）',
    generateSimilarQuestion: '類題を生成（現在の設問を置換）',
    generatingQuestion: '生成中...',
    showAdvanced: '詳細を表示',
    hideAdvanced: '詳細を閉じる',
    backToQuestions: '設問一覧に戻る',
  },
  labels: {
    questions: '要確認の設問',
    assessmentDetails: '課題の詳細',
    assessmentDetailsDescription: 'この下書きの課題情報を更新します。',
    questionEditor: '設問を確認',
    questionEditorDescription: '',
    questionSettings: '詳細の確認',
    questionSettingsDescription: 'タイプ、配点、解答キーを設定します。',
    studentPreview: '学生プレビュー',
    studentPreviewDescription: '学生に表示される形式で内容を確認します。',
    showAnswers: '解答を表示',
    showPoints: '配点を表示',
    railActions: {
      add: '追加',
      moveUp: '上へ',
      moveDown: '下へ',
      delete: '削除',
    },
    title: 'タイトル',
    category: 'カテゴリ',
    subject: '科目',
    grade: '学年',
    customCategory: 'カスタムカテゴリ名',
    description: '説明',
    prompt: '設問文',
    stepPrompt: '1. 問題文',
    stepAnswer: '2. 解答',
    stepScoring: '3. 配点',
    choices: '選択肢',
    correctLabel: '正解ラベル',
    correctText: '正解テキスト',
    estimatedCorrectRate: '推定正答率',
    estimatedAverage: '推定平均',
    points: '配点',
    order: '順序',
    questionType: '設問タイプ',
    editableHint: 'ハイライトされた項目をクリックして編集できます。',
    go: '移動',
    totalPoints: '合計点',
    questionsCountSummary: (questions: number) => `${questions}問`,
    missingPoints: (value: number) => `配点未設定: ${value}問`,
    questionsPointsSummary: (questions: number, points: number) => `${questions}問 / ${points}点`,
    pointsMissingShort: '未設定',
    questionTypeShortLabels: {
      multiple_choice: '選択',
      true_false: '正誤',
      short_answer: '短答',
      written: '記述',
      other: 'その他',
    },
    mobileQuestionsTab: '設問',
    mobileEditorTab: '編集',
  },
  placeholders: {
    selectAssessment: '課題を選択',
    chooseCategory: 'カテゴリを選択',
    subject: '例: 日本語',
    grade: '例: 小学6年',
    customCategory: 'カスタムカテゴリの場合のみ',
    description: '他の先生向けに課題の説明を入力',
    prompt: '設問文を入力',
    correctLabel: 'A',
    correctText: '正解の内容',
    correctExample: '解答例',
    points: '2',
    choicePrefix: '選択肢',
  },
  empty: {
    noQuestions: '設問はまだありません。',
    selectQuestion: '設問を選択するか、新しい設問を追加してください。',
    selectQuestionSettings: '設問を選択して設定を編集します。',
  },
  status: {
    unsavedTitle: '未保存の変更',
    unsavedMessage: '下書きに未保存の編集があります。',
    savingTitle: '保存中...',
    savingMessage: '下書きを更新しています。',
    savedTitle: '保存済み',
    allSaved: 'すべて保存済みです。',
    pendingSwitch: '保存または破棄して課題を切り替えてください。',
    pendingNew: '保存または破棄して新規課題を作成してください。',
    lastSavedPrefix: '最終保存',
    justNow: 'たった今',
    minutesAgo: (value: number) => `${value}分前`,
    hoursAgo: (value: number) => `${value}時間前`,
    parsingInProgressTitle: '解析中です',
    parsingInProgressBody:
      '設問の抽出中です。上書きを防ぐため、設問編集と保存は一時的にロックされています。',
    parsingFailedTitle: '解析に失敗しました',
    parsingFailedBody:
      'アップロードは完了しましたが解析に失敗しました。アップロード画面から再試行してください。',
    parsingFailedAction: 'アップロードへ',
    parsingLockedSaveError: '解析完了まで保存できません。しばらくお待ちください。',
    parsingLockedHint: '解析が完了すると設問編集は自動で解除されます。',
    preparingEditorTitle: 'エディタを準備しています',
    preparingEditorBody: '設問と下書きを読み込んでいます。まもなく表示されます。',
    generationLockedHint: '設問を再生成中です。完了まで編集は一時停止されます。',
    parsingQueuedLabel: '待機中',
    parsingRunningLabel: '解析中',
  },
  notices: {
    created: '課題を作成しました。',
    duplicated: '課題を複製しました。',
    saved: '変更を保存しました。',
    reordered: '設問の順番を更新しました。',
    questionGenerated: '設問を更新しました。',
    similarQuestionGenerated: '類題で現在の設問を置換しました。',
    draftStored: '変更は現在の下書きに保存されています。',
  },
  errors: {
    actionFailedTitle: '操作に失敗しました',
    generic: 'エラーが発生しました。もう一度お試しください。',
  },
  select: {
    assessmentsLabel: '課題',
    newAssessmentOption: '新規課題（空）',
  },
  questionList: {
    untitled: '無題の設問',
    prefix: '問',
    reviewCounter: '要確認:',
    statusLabels: {
      reviewed: '確認済み',
      'needs-review': '要確認',
      untouched: '未確認',
    },
  },
  defaults: {
    untitledAssessment: '無題の課題',
    copyLabel: 'コピー',
  },
  questionTypeLabels,
  previewDefaults: {
    trueLabel: '正しい',
    falseLabel: '誤り',
    shortAnswerPlaceholder: '解答欄',
    writtenPlaceholder: '記述解答',
  },
  assessmentCategoryLabels,
} as const;
