import type { AssessmentCategory, QuestionType } from '@/lib/assessment-api';

type CategoryOptionValue = Exclude<AssessmentCategory, null> | 'none';

const questionTypeLabels: Record<QuestionType, string> = {
  multiple_choice: 'Multiple choice',
  true_false: 'True/False',
  short_answer: 'Short answer',
  written: 'Written',
  other: 'Other',
};

const assessmentCategoryLabels: Array<{ value: CategoryOptionValue; label: string }> = [
  { value: 'none', label: 'Uncategorized' },
  { value: 'quiz', label: 'Quiz' },
  { value: 'midterm', label: 'Midterm' },
  { value: 'final', label: 'Final' },
  { value: 'practice', label: 'Practice' },
  { value: 'other', label: 'Other' },
];

export const EDITOR_COPY = {
  header: {
    draftLabel: 'Draft',
    titlePrefix: 'Review Generated Assessment:',
    subtitle: '',
    studentViewLabel: 'Preview',
    assessmentSettingsLabel: 'Settings',
    printEditorLabel: 'Print',
  },
  layoutOptions: {
    studio: 'Studio',
    document: 'Document',
  },
  a11y: {
    layoutToggle: 'Editor layout',
  },
  actions: {
    newAssessment: 'New',
    duplicateAssessment: 'Duplicate',
    more: 'More',
    saveChanges: 'Save',
    save: 'Save',
    confirmNext: 'Save & Next',
    discard: 'Discard',
    close: 'Close',
    studentView: 'Student view',
    addQuestion: 'Add question',
    moveUp: 'Move up',
    moveDown: 'Move down',
    deleteQuestion: 'Delete question',
    addChoice: 'Add choice',
    generateTargetQuestion: 'Rewrite to 60% (Replace current)',
    generateSimilarQuestion: 'Generate Similar (Replace current)',
    generatingQuestion: 'Generating...',
    showAdvanced: 'Show advanced',
    hideAdvanced: 'Hide advanced',
    backToQuestions: 'Back to questions',
  },
  labels: {
    questions: 'Questions to review',
    assessmentDetails: 'Assessment details',
    assessmentDetailsDescription: 'Update the assessment metadata for this draft.',
    questionEditor: 'Review this question',
    questionEditorDescription: '',
    questionSettings: 'Review details',
    questionSettingsDescription: 'Set the type, scoring, and answer key.',
    studentPreview: 'Student preview',
    studentPreviewDescription: 'Review the assessment as students will see it.',
    showAnswers: 'Show answers',
    showPoints: 'Show points',
    railActions: {
      add: 'Add',
      moveUp: 'Up',
      moveDown: 'Down',
      delete: 'Del',
    },
    title: 'Title',
    category: 'Category',
    subject: 'Subject',
    grade: 'Grade',
    customCategory: 'Custom category label',
    description: 'Description',
    prompt: 'Prompt',
    stepPrompt: '1. Prompt',
    stepAnswer: '2. Answer',
    stepScoring: '3. Points',
    choices: 'Choices',
    correctLabel: 'Correct answer label',
    correctText: 'Correct answer text',
    estimatedCorrectRate: 'Estimated correct',
    estimatedAverage: 'Estimated average',
    points: 'Points',
    order: 'Order',
    questionType: 'Question type',
    editableHint: 'Click any highlighted field to edit.',
    go: 'Go',
    totalPoints: 'Total points',
    questionsCountSummary: (questions: number) => `${questions}Q`,
    missingPoints: (value: number) => `Points missing: ${value}`,
    questionsPointsSummary: (questions: number, points: number) => `${questions}Q / ${points} pts`,
    pointsMissingShort: 'Unset',
    questionTypeShortLabels: {
      multiple_choice: 'MC',
      true_false: 'TF',
      short_answer: 'Short',
      written: 'Written',
      other: 'Other',
    },
    mobileQuestionsTab: 'Questions',
    mobileEditorTab: 'Editor',
  },
  placeholders: {
    selectAssessment: 'Select assessment',
    chooseCategory: 'Choose category',
    subject: 'e.g. Japanese',
    grade: 'e.g. Grade 6',
    customCategory: 'Only required for custom categories',
    description: 'Describe the assessment for other teachers',
    prompt: 'Enter the question prompt',
    correctLabel: 'A',
    correctText: 'Answer text',
    correctExample: 'Example answer',
    points: '2',
    choicePrefix: 'Choice',
  },
  empty: {
    noQuestions: 'No questions yet.',
    selectQuestion: 'Select a question to start editing or add a new one.',
    selectQuestionSettings: 'Select a question to edit settings.',
  },
  status: {
    unsavedTitle: 'Unsaved changes',
    unsavedMessage: 'Your draft has unsaved edits.',
    savingTitle: 'Saving...',
    savingMessage: 'Updating this draft now.',
    savedTitle: 'All changes saved',
    allSaved: 'All changes are saved.',
    pendingSwitch: 'Save or discard to switch assessments.',
    pendingNew: 'Save or discard to start a new assessment.',
    lastSavedPrefix: 'Last saved',
    justNow: 'just now',
    minutesAgo: (value: number) => `${value}m ago`,
    hoursAgo: (value: number) => `${value}h ago`,
    parsingInProgressTitle: 'Parsing in progress',
    parsingInProgressBody:
      'Questions are still being extracted. Question editing and saving are temporarily locked to prevent overwrite.',
    parsingFailedTitle: 'Parsing failed',
    parsingFailedBody: 'The upload succeeded but parsing failed. Return to upload to retry.',
    parsingFailedAction: 'Go to upload',
    parsingLockedSaveError: 'Please wait for parsing to finish before saving.',
    parsingLockedHint: 'Question editing unlocks automatically when parsing finishes.',
    preparingEditorTitle: 'Preparing editor',
    preparingEditorBody: 'Loading questions and draft state. This will be ready shortly.',
    generationLockedHint: 'Regenerating this question. Editing is paused until it finishes.',
    parsingQueuedLabel: 'Queued',
    parsingRunningLabel: 'Running',
  },
  notices: {
    created: 'Assessment created.',
    duplicated: 'Assessment duplicated.',
    saved: 'Changes saved.',
    reordered: 'Question order updated.',
    questionGenerated: 'Question updated.',
    similarQuestionGenerated: 'Similar variant replaced the current question.',
    draftStored: 'Your changes are stored in the current draft.',
  },
  errors: {
    actionFailedTitle: 'Action failed',
    generic: 'Something went wrong. Try again.',
  },
  select: {
    assessmentsLabel: 'Assessments',
    newAssessmentOption: 'New assessment (blank)',
  },
  questionList: {
    untitled: 'Untitled question',
    prefix: 'Q',
    reviewCounter: 'Questions to review:',
    statusLabels: {
      reviewed: 'Reviewed',
      'needs-review': 'Needs review',
      untouched: 'Untouched',
    },
  },
  defaults: {
    untitledAssessment: 'Untitled Assessment',
    copyLabel: 'Copy',
  },
  questionTypeLabels,
  previewDefaults: {
    trueLabel: 'True',
    falseLabel: 'False',
    shortAnswerPlaceholder: 'Short answer',
    writtenPlaceholder: 'Written response',
  },
  assessmentCategoryLabels,
} as const;
